# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/Xilinx_Vivoda/DDS_Sin/DDS_Sin.srcs/sources_1/ip/DDS_ROM/DDS_ROM.xci
# IP: The module: 'DDS_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Xilinx_Vivoda/DDS_Sin/DDS_Sin.srcs/sources_1/ip/DDS_ROM/DDS_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA/Xilinx_Vivoda/DDS_Sin/DDS_Sin.srcs/sources_1/ip/DDS_ROM/DDS_ROM.xci
# IP: The module: 'DDS_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Xilinx_Vivoda/DDS_Sin/DDS_Sin.srcs/sources_1/ip/DDS_ROM/DDS_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DDS_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
